### ISSUE TITLE
编译的docker镜像有点问题

### ISSUE THREAD

**Issue by xupengyao** [rock-app/fabu.love#112]
直接从github拉取这份代码下来编译docker镜像运行正常，但是我把这份代码推送到自己的gitlab之后再拉取下来编译，发现上传安装包的时候有问题：
`Not sure what to do with typed value of type 0x4, falling back to reading an uint32.
/opt/server/controllers/upload.js:365
                if (typeof data['application-icon-' + iconSize[i]] !== 'undefined') {
                               ^

TypeError: Cannot read property 'application-icon-640' of undefined
    at apkParser3 (/opt/server/controllers/upload.js:353:28)
    at /opt/server/library/apkparser/apkparser.js:22:14
    at exithandler (child_process.js:301:5)
    at ChildProcess.errorhandler (child_process.js:313:5)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fabu@1.0.0 start: `babel-node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fabu@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-22T08_58_14_219Z-debug.log`
        麻烦给与指点，谢谢！

**Comment by yolo2h** [comment]
我这里也出现了，解决办法是给`server/library/apkparser/`下的`aapt-linux`和`aapt-osx`执行权限。

**Comment by answer-huang** [comment]
@xupengyao @yolo2h 可以试下这个仓库, 更新了不少依赖和文件:

https://github.com/answer-huang/fabu.love

**Comment by answer-huang** [comment]
麻烦试下最新 master 分支的版本.
