### ISSUE TITLE
cnpm install error

### ISSUE THREAD

**Issue by iwkoo** [rock-app/fabu.love#117]
✖ Install fail! ShasumNotMatchError: real sha1:46bc2d235f16d9024c16137e096ca7b665aeb319 not equal to remote:47e2e234638eede4caa52d961e3a7459b55530ef (mongoose@5.9.6)
ShasumNotMatchError: real sha1:46bc2d235f16d9024c16137e096ca7b665aeb319 not equal to remote:47e2e234638eede4caa52d961e3a7459b55530ef (mongoose@5.9.6)
    at IncomingMessage.readstream.on (/usr/lib/node_modules/cnpm/node_modules/npminstall/lib/download/npm.js:631:21)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:978:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
npminstall version: 3.27.0
npminstall args: /usr/bin/node /usr/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/root/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://r.npm.taobao.org --no-cache

**Comment by answer-huang** [comment]
可以试下这个仓库, 有问题可以提 issue:
https://github.com/answer-huang/fabu.love
