### ISSUE TITLE
apk上传服务器后报错

### ISSUE THREAD

**Issue by IsaiahKing** [rock-app/fabu.love#99]
Unhandled rejection Error: invalid signature: 0x0
    at /root/fabu.love/server/node_modules/_unzipper@0.9.15@unzipper/lib/parse.js:62:26
    at tryCatcher (/root/fabu.love/server/node_modules/_bluebird@3.4.7@bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/fabu.love/server/node_modules/_bluebird@3.4.7@bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/root/fabu.love/server/node_modules/_bluebird@3.4.7@bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/root/fabu.love/server/node_modules/_bluebird@3.4.7@bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/root/fabu.love/server/node_modules/_bluebird@3.4.7@bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/root/fabu.love/server/node_modules/_bluebird@3.4.7@bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/root/fabu.love/server/node_modules/_bluebird@3.4.7@bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)

**Comment by answer-huang** [comment]
@IsaiahKing 试下这个版本, 还有问题可以提 issue:

https://github.com/answer-huang/fabu.love
